### ISSUE TITLE
Slow orthograph-analyzer

### ISSUE THREAD

**Issue by KristinaGagalova** [mptrsen/Orthograph#34]
Hi, 
I am using orthoDB plants to group my own sequences in orthogroups.
I managed to do all the steps but now orthograph-analyzer is taking a while. Attched the log file for the alignments
Do you maybe have any sugestion on how to speed it up?
Thank you in advance
[alignment.zip](https://github.com/mptrsen/Orthograph/files/4166513/alignment.zip)

**Comment by mptrsen** [comment]
Use more threads with `--num-threads` (can also be set in the config).

What alignment program are you using? It looks like there are so many sequences that the alignment takes ages.

Generally, with a new ortholog set, the first orthograph-analyzer run will take loooong because it needs to create alignments and HMMs. Once these are done, subsequent analyzer runs can use those and will be _much_ faster.

**Comment by mptrsen** [comment]
Closed, could not reproduce
